const template_CIA = {
    "perceivedUnhappiness": "",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "",
    "generateInterestDetails": "",
    "haveAnnouncement": "",
    "announcementTypes": [],
    "haveNotification": "",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "",
    "actionRequiredDetails": "",
    "dataInsightDetails": "",
    "initiativesDetails": "",
    "eventWriteUp": ``
}

// ASG
const ROW4_DETAILS =
{
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-31T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Custom",
    "frequencyInterval": 1,
    "customFrequency": "Monthly",
    "selectedDay": "Last Working Day of Month",
    "title": "AP and GSTV eligibility adjustments",
    "scheme": "Assurance Package (AP), GST Voucher (GSTV)",
    "description": "Batch adjustment for citizens with changes to eligibility",
    "affectedCohortDescription": "Eligible Singaporeans aged 21 and above",
    "estimatedCohortSize": 100,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Chua Mei Ling",
    "OICEmail": "Chua.Mei.Ling@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW4_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "Yes",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": `Advise eligible citizens who have not sign-up, to sign up (online or form) by 31 May of next year`,
    "dataInsightDetails": "",
    "initiativesDetails": "",
    "eventWriteUp": ``
}

const ROW5_DETAILS_W1 = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-11-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Payment of AP Cash",
    "scheme": "Assurance Package (AP) ",
    "description": "Regular payment of AP Cash, AP SB, COL SP",
    "affectedCohortDescription": "Eligible Singaporeans aged 21 and above",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW5_DETAILS_W2 = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-08T16:00:00.000Z"),
    "endDate": new Date("2025-11-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Payment of AP Cash",
    "scheme": "Assurance Package (AP) ",
    "description": "Regular payment of AP Cash, AP SB, COL SP",
    "affectedCohortDescription": "Eligible Singaporeans aged 21 and above",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW5_DETAILS_W3 = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-11-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Payment of AP Cash",
    "scheme": "Assurance Package (AP) ",
    "description": "Regular payment of AP Cash, AP SB, COL SP",
    "affectedCohortDescription": "Eligible Singaporeans aged 21 and above",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW6_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-11-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Regular payment to AP MTS",
    "scheme": "Assurance Package (AP) ",
    "description": "Regular payment to AP MTS",
    "affectedCohortDescription": "Eligible Singaporeans aged 20 & below, and 55 & above",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW7_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Regular payment of GSTV - Cash",
    "scheme": "GST Voucher (GSTV)",
    "description": "Regular payment of GSTV - Cash",
    "affectedCohortDescription": "Eligible Singaporeans aged 21 and above",
    "estimatedCohortSize": 500,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW8_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Regular payment of GSTV - MediSave",
    "scheme": "GST Voucher (GSTV)",
    "description": "Regular payment of GSTV - MediSave",
    "affectedCohortDescription": "Eligible Singaporeans aged 65 & above",
    "estimatedCohortSize": 250,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW9_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Regular payment of ESB, MSB, RSB",
    "scheme": "Majulah Package (MP)",
    "description": "Regular payment of ESB, MSB, RSB",
    "affectedCohortDescription": "Eligible Singaporeans aged 50 & above in 2023",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW10_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "One-off MediSave Bonus (MTU)",
    "scheme": "Medisave",
    "description": "Regular payment of MTU",
    "affectedCohortDescription": "Eligible Singaporeans aged 21 to 50 in 2024",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW11_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-08T16:00:00.000Z"),
    "endDate": new Date("2025-11-28T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notify members of SSS payment",
    "scheme": "Silver Support Scheme (SSS)",
    "description": "Send SMS and letter to eligible citizens to notify SSS payment",
    "affectedCohortDescription": "Eligible Singaporeans aged 65 and above",
    "estimatedCohortSize": 600,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW12_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-28T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Allot SEP/ Dual Status Worker (DSW) WIS",
    "scheme": "Workfare Income Supplement (WIS)",
    "description": "Monthly run to allot SEP/ Dual Status Worker (DSW) WIS after capturing MediSave contributions made in the preceding month/ adjustments due to successful appeals",
    "affectedCohortDescription": "Low-wage workers",
    "estimatedCohortSize": 10000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Chua Mei Ling",
    "OICEmail": "Chua.Mei.Ling@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW13_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-02-28T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Allot EEs WIS",
    "scheme": "Workfare Income Supplement (WIS)",
    "description": "Monthly run to allot EEs WIS after capturing late CPF contributions/ adjustments",
    "affectedCohortDescription": "Low-wage workers",
    "estimatedCohortSize": 10000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Chua Mei Ling",
    "OICEmail": "Chua.Mei.Ling@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW14_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-28T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "WIS / TCA Monthly Payment",
    "scheme": "Workfare Income Supplement (WIS)",
    "description": "Workfare Income Supplement (WIS)/Training Commitment Award (TCA) Monthly Payment. Notification letters/SMS will be sent out.",
    "affectedCohortDescription": "Low-wage workers",
    "estimatedCohortSize": 350000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW15_DETAILS_1 = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-08T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "2025 Assurance Package - Senior Bonus",
    "scheme": "Assurance Package (AP)",
    "description": "Press Release by MOF for 2025 AP SB and MA which will be credited in February 2025",
    "affectedCohortDescription": "AP SB: Eligible Singaporeans aged 21 and above",
    "estimatedCohortSize": 750000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW15_DETAILS_2 = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-08T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "2025 Assurance Package - Medisave",
    "scheme": "Assurance Package (AP)",
    "description": "Press Release by MOF for 2025 AP SB and MA which will be credited in February 2025",
    "affectedCohortDescription": "AP MA: Eligible Singaporeans aged 20 & below, and 55 & above",
    "estimatedCohortSize": 2000000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW15_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "Yes",
    "generateInterestDetails": "",
    "haveAnnouncement": "Yes",
    "announcementTypes": ["Press Release"],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "No",
    "actionRequiredDetails": "",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `NA`
}

const ROW16_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Daily",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Failed Bank Account verification notification",
    "scheme": "CD",
    "description": "Send letter to inform citizens with invalid bank account to resubmit their details",
    "affectedCohortDescription": "Singaporeans with invalid bank account details in our record",
    "estimatedCohortSize": 100,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    // "reportStatus": "Completed"
}

// COM
const ROW24_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-28T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 2,
    "customFrequency": null,
    "selectedDay": null,
    "title": "InTouch eDM",
    "scheme": "",
    "description": "InTouch eDM",
    "affectedCohortDescription": "Subscribers",
    "estimatedCohortSize": 100000,
    "cluster": "PCD",
    "group": "COM",
    "department": "MPD",
    "OIC": "DD(MP) Joanne Lim",
    "OICEmail": "Joanne.Lim@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW25_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Members' Affinity Survey 2024",
    "scheme": "",
    "description": "",
    "affectedCohortDescription": "Active CPF members from 21 to 70 years old",
    "estimatedCohortSize": 15000,
    "cluster": "PCD",
    "group": "COM",
    "department": "MPD",
    "OIC": "DD(MP) Valerie Ong",
    "OICEmail": "Valerie.Ong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW25_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "Yes",
    "notificationTypes": ["Invitational Letters"],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": "Respond to survey",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `NA`
}

const ROW26_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-21T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Press release on closure of SA",
    "scheme": "CPF Special Account (SA)",
    "description": "Press release on closure of SA",
    "affectedCohortDescription": "Press release on closure of SA",
    "estimatedCohortSize": 5000000,
    "cluster": "PCD",
    "group": "COM",
    "department": "MPD",
    "OIC": "DD(MP) Adeline Leu",
    "OICEmail": "Adeline.Leu@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW26_CIA = {
    "perceivedUnhappiness": "Yes",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "Yes",
    "announcementTypes": ["Press Release"],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "No",
    "actionRequiredDetails": "",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`
}

// DSG
const ROW45_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Trial for Inmates to Access CPF E-Services",
    "scheme": "NA",
    "description": "Trial for inmates to access CPF e-services via Singpass (From September 2024)",
    "affectedCohortDescription": "Inmates who can surf CPF website",
    "estimatedCohortSize": 120,
    "cluster": "IDS",
    "group": "DSG",
    "department": "DSD",
    "OIC": "M (DSD) Lee Yen Ching",
    "OICEmail": "Lee.Yen.Ching@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW46_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-30T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Sunset of Email Receiver Checker",
    "scheme": "NA",
    "description": "Sunset of Email Receiver Checker",
    "affectedCohortDescription": "Members who accessed Email Receiver Checker",
    "estimatedCohortSize": 10000,
    "cluster": "IDS",
    "group": "DSG",
    "department": "DSD",
    "OIC": "M (DSD) Lee Yen Ching",
    "OICEmail": "Lee.Yen.Ching@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW47_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-06T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Recruit research study participants for Write to Us & Text Us",
    "scheme": "Write to Us & Text Us (WTU)",
    "description": "Recruiting participants for research study to understand members’ experience of Write to Us & Text Us",
    "affectedCohortDescription": "Members who used Write to Us (WTU) in the past 1 month.",
    "estimatedCohortSize": 200,
    "cluster": "IDS",
    "group": "DSG",
    "department": "DSD",
    "OIC": "SM(DS) Tan Yong Heng",
    "OICEmail": "Tan.Yong.Heng@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW48_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-06T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Recruit research study participants for CPF Translated Webpages",
    "scheme": "",
    "description": "Recruiting participants for research study to understand members’ experience translated CPF pages",
    "affectedCohortDescription": "Members who used any website/mobile app's translation feature (i.e. Chinese, Malay, or Tamil) in past 3 months.",
    "estimatedCohortSize": 15000,
    "cluster": "IDS",
    "group": "DSG",
    "department": "DSD",
    "OIC": "SM(DS) Tan Yong Heng",
    "OICEmail": "Tan.Yong.Heng@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW49_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-06T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Recruiting participants to test design of new digital service ",
    "scheme": "",
    "description": "Recruiting participants to test design of new digital service ",
    "affectedCohortDescription": "Members who have provided or received assistance on a CPF matter through a digital CPF channel within the past 3 months.",
    "estimatedCohortSize": 8000,
    "cluster": "IDS",
    "group": "DSG",
    "department": "DSD",
    "OIC": "AD (DS) Rahman Ahmad",
    "OICEmail": "Rahman.Ahmad@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW50_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-27T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "searchCentral A/B test against SearchSG",
    "scheme": "",
    "description": "searchCentral A/B test against SearchSG",
    "affectedCohortDescription": "Members who use CPF website.",
    "estimatedCohortSize": 1000000,
    "cluster": "IDS",
    "group": "DSG",
    "department": "DSD",
    "OIC": "M(DS) Tee Kai Qi",
    "OICEmail": "Tee.Kai.Qi@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW50_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "No",
    "haveActionRequired": "No",
    "actionRequiredDetails": "",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `NA`
}

// CED
const ROW53_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-15T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Letters of Demand/Notifications Informing Employers of Composition Amount Imposed or CPF Arrears Owed",
    "scheme": "",
    "description": "Letters of Demand/Notifications Informing Employers/Platform Operators of Composition Amount Imposed or CPF Arrears Owed ",
    "affectedCohortDescription": "Employers/Platform Operators who have defaulted on payment of contributions for their employees/platform workers.",
    "estimatedCohortSize": 3000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "DD(CED) Lin Ziping",
    "OICEmail": "Lin.Ziping@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW54_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-15T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification Letters to Attend Court Sessions or Interviews",
    "scheme": "",
    "description": "Notification Letters to Attend Court Sessions or Interviews",
    "affectedCohortDescription": "Employers/Platform Operators with ongoing prosecution actions against them",
    "estimatedCohortSize": 1500,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "DD(CED) Lin Ziping",
    "OICEmail": "Lin.Ziping@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW55_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-15T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification to Employers/Platform Operators of Waivers/Refund of Late Payment Interests Charged",
    "scheme": "",
    "description": "Notification Letters Informing Employers/Platform Operators of Waivers or Refund of Late Payment Interests Charged",
    "affectedCohortDescription": "Employers/Platform Operators eligible for waiver or refund of late payment interests charged",
    "estimatedCohortSize": 500,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "DD(CED) Lin Ziping",
    "OICEmail": "Lin.Ziping@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW56_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-15T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification to Employers/Platform Operators regarding Deactivation of CSN",
    "scheme": "",
    "description": "Notification Letters Informing Employers/Platform Operators on Deactivation of CSN",
    "affectedCohortDescription": "Employers/Platform Operators who have ceased to employ Singaporeans or Permanent Residents",
    "estimatedCohortSize": 3000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "DD(CED) Lin Ziping",
    "OICEmail": "Lin.Ziping@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW57_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-15T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Email reminder to Employers/Platform Operators to pay overdue CPF contributions",
    "scheme": "",
    "description": "Email blast to remind Employers/Platform Operators and employees/platform workers to pay their overdue CPF contributions",
    "affectedCohortDescription": "Employers/Platform Operators who have defaulted on payment of contributions for their employees/platform workers",
    "estimatedCohortSize": 9000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "SM(CED) Siva",
    "OICEmail": "Siva@cpf.com.sg",
    // "reportStatus": "Completed"
}

// CSD
const ROW60_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-03-01T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF EzPay's Direct Link-up and Mobile Platforms increase in CPF OW ceiling Announcement",
    "scheme": "",
    "description": "Announcement on CPF EZPay's Direct Link-up and mobile platforms to inform employers on the increase in CPF OW ceiling to $7400 and CPF contribution rate change for senior workers from 1 Jan 2025",
    "affectedCohortDescription": "all employers using CPF EZPay's direct link-up and mobile platform",
    "estimatedCohortSize": 90000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "SM(CS) Anuradha ",
    "OICEmail": "Anuradha@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW61_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF Contribution Alert",
    "scheme": "",
    "description": "CPF Contribution Alert to employers",
    "affectedCohortDescription": "'Employees who received current month mandatory CPF contributions and has registered email address or downloaded CPF Mobile and enabled personalised notifications.  Exclude 1st and 2nd year SPR, pension employees and employees tagged as  'classified'. ",
    "estimatedCohortSize": 100001,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "SM(CS) Anuradha ",
    "OICEmail": "Anuradha@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW62_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-03-01T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF EzPay's Main Menu Page Annnouncment Regarding increase in CPF OW ceiling",
    "scheme": "",
    "description": "Announcement on CPF EZPay's main menu page to inform employers on the increase in CPF OW ceiling to $7400 and CPF contribution rate change for senior workers from 1 Jan 2025",
    "affectedCohortDescription": "''e' employers using EZPay",
    "estimatedCohortSize": 100001,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CED",
    "OIC": "SM(CS) Anuradha ",
    "OICEmail": "Anuradha@cpf.com.sg",
    // "reportStatus": "Completed"
}

// SED
const ROW67_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-08T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Inform FIs of SEP Defaulters",
    "scheme": "MediSave",
    "description": "Collaboration with Financial Institutions (FIs) – listing sent to FIs to inform them of the agents (i.e. self-employed persons) who are defaulting on their MediSave obligations",
    "affectedCohortDescription": "SEP defaulters",
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "DD(SED) Ling Weiyin",
    "OICEmail": "Ling.Weiyin@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW68_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-12T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification to SEP Defaulters",
    "scheme": "MediSave",
    "description": `Notifications to licensed self-employed persons (SEPs) who are defaulting on their MediSave obligations 
                    a. To SEP defaulters who are shorter-term (or not under b below) licence holders
                    b. To SEP defaulters who are longer-term (ACRA licences) or lifetime licence holders (MAS and EMA licences)`,
    "affectedCohortDescription": "SEP defaulters",
    "estimatedCohortSize": 7000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "DD(SED) Ling Weiyin",
    "OICEmail": "Ling.Weiyin@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW69_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-12T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notice of CPF Contributions (NOC) for Self-Employed Persons (SEPs)",
    "scheme": "MediSave",
    "description": `Notifications to SEPs,
                    i.e. Notice of CPF contributions (NOC) for self-employed persons (SEPs),
                    informing them of the required MediSave contributions after annual income assessment by IRAS`,
    "affectedCohortDescription": "SEPs",
    "estimatedCohortSize": 250000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "DD(SED) Ling Weiyin",
    "OICEmail": "Ling.Weiyin@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW70_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-12T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Implementation of Platform Workers CPF Contributions ",
    "scheme": "CPF Support Scheme (PCTS)",
    "description": `    a) Platform operators will start deducting CPF contributions from platform workers' Jan 2025 earnings and submit to the Board by 14 of the following month
                        (for example, contribution for Jan 2025 to be submitted by 14 Feb 2025).
                        There might be queries on POs deducting CPF contributions. 
                        b) Jan 2025 is the first work month for Platform Workers CPF Support Scheme (PCTS).
                        PCTS for first work month of Jan 2025 will be paid in Mar 2025.
                        There might be queries on when PCTS payments will be received. `,
    "affectedCohortDescription": "Platform Workers",
    "estimatedCohortSize": 100001,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "DD(SED) Kyle Huang",
    "OICEmail": "Kyle.Huang@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW70_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": "Good-to-know information",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `Jan 2025 will be the first month that Platform Operators start deducting CPF contributions from platform worker's earnings. PWs, like employees, will receive CPF Contribution Alert, once the contributions have been credited (~14 Feb)
                    Jan 2025 is the first work month for which platform workers' eligibility for PCTS will be assessed. However, payment will be made in Mar 2025. `
}

// HCP
const ROW76_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSV Care First Withdrawal Letters",
    "scheme": "MediSave, MSV Care",
    "description": "CPF members aged 40 and above who has applied to withdraw from his MA under MSV Care for himself/his spouse will receive this letter",
    "affectedCohortDescription": "CPF members aged 40 and above who has applied to withdraw from his MA under MSV Care",
    "estimatedCohortSize": 190,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HCP",
    "OIC": "DD(HCP) Angela Kwek",
    "OICEmail": "Angela.Kwek@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW77_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSV Care Drop-in-Tier Letters",
    "scheme": "MSV Care",
    "description": "CPF members who have been withdrawing under MediSave and there is now a drop in tier for the amount they are able to withdraw will receive this letter. ",
    "affectedCohortDescription": "CPF members who have been withdrawing under MediSave and there is now a drop in tier for the amount they are able to withdraw",
    "estimatedCohortSize": 30,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HCP",
    "OIC": "DD(HCP) Angela Kwek",
    "OICEmail": "Angela.Kwek@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW78_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CSHL Payouts Notification",
    "scheme": "CareShield Life",
    "description": "Insureds who are claiming under CareShield Life will receive a notification informing them that their CareShield Life payout has been credited to his bank account.",
    "affectedCohortDescription": "Insureds who are claiming under CareShield Life",
    "estimatedCohortSize": 1931,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HCP",
    "OIC": "DD(HCP) Angela Kwek",
    "OICEmail": "Angela.Kwek@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW79_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSV Care Payouts Notification",
    "scheme": "MSV Care",
    "description": "CPF members aged 40 and above who has applied to received MSV Care payouts will receive a notification informing them that their MSV Care payout has been credited to his bank account. ",
    "affectedCohortDescription": "CPF members aged 40 and above who has applied to received MSV Care payouts",
    "estimatedCohortSize": 2250,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HCP",
    "OIC": "DD(HCP) Angela Kwek",
    "OICEmail": "Angela.Kwek@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW80_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "ESH Payouts Notification",
    "scheme": "Eldershield",
    "description": "Insureds who are claiming under ElderShield will receive a notification informing them that their ElderShield payout has been credited to his bank account.",
    "affectedCohortDescription": "Insureds who are claiming under ElderShield",
    "estimatedCohortSize": 6890,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HCP",
    "OIC": "DD(HCP) Angela Kwek",
    "OICEmail": "Angela.Kwek@cpf.com.sg",
    // "reportStatus": "Completed"
}

// HID
const ROW84_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-22T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL Premium Notice Letter to Payer",
    "scheme": "MSHL",
    "description": "MSHL Premium Notice Letter to Payer",
    "affectedCohortDescription": "Existing insureds with MSHL renewal within following 2 months.",
    "estimatedCohortSize": 74200,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Anita Hong,",
    "OICEmail": "Anita.Hong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW85_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-12T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Custom",
    "frequencyInterval": 1,
    "customFrequency": "Monthly",
    "selectedDay": "Second Sunday of the Month",
    "title": "MSHL Successful Premium Deduction Letters",
    "scheme": "MSHL",
    "description": "MSHL Successful Premium Deduction Letters",
    "affectedCohortDescription": "Insureds with a change in premium amount or insufficient MA.",
    "estimatedCohortSize": 6400,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Jamie Siew,",
    "OICEmail": "Jamie.Siew@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW86_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-09T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL Unsuccessful Premium Deduction Letters",
    "scheme": "MSHL",
    "description": "MSHL Unsuccessful Premium Deduction Letters",
    "affectedCohortDescription": "Insureds with a change in premium amount or insufficient MA.",
    "estimatedCohortSize": 6100,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW87_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL Auto-Cover Letters for New Insureds",
    "scheme": "MSHL",
    "description": "MSHL Auto-Cover Letters for New Insureds",
    "affectedCohortDescription": "Eligible newborn Singaporeans, new Singapore Citizens and Permanent Residents",
    "estimatedCohortSize": 8000,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Joycelyn Tan",
    "OICEmail": "Joycelyn.Tan@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW88_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL Payer Management Letters",
    "scheme": "MSHL",
    "description": "MSHL Payer Management Letters",
    "affectedCohortDescription": "Members who have submitted COP/ SPP request and insureds who are ANB > 21 years old.",
    "estimatedCohortSize": 460,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW89_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL Family Support Letters",
    "scheme": "MSHL",
    "description": "MSHL Family Support Letters",
    "affectedCohortDescription": "Family members of insureds who have unsuccessful premium deduction twice and have paid for insured’s medical or insurance premium.",
    "estimatedCohortSize": 320,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW90_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL Premium Adjustment Letters",
    "scheme": "MSHL",
    "description": "MSHL Premium Adjustment Letters",
    "affectedCohortDescription": "Insureds with a change in subsidies.",
    "estimatedCohortSize": 40,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Jamie Siew",
    "OICEmail": "Jamie.Siew@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW91_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MediSave Grant for Newborns Letters",
    "scheme": "MSHL",
    "description": "MediSave Grant for Newborns Letters",
    "affectedCohortDescription": "Eligible newborn Singaporeans; successful appeals and new SCs.",
    "estimatedCohortSize": 20,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Grace Chua",
    "OICEmail": "Grace.Chua@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW92_93_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "MSHL/CSHL Demand Note to Enforced Premium Defaulters (Sent out by IRAS)",
    "scheme": "MSHL, CSHL",
    "description": "MSHL/CSHL Demand Note to Enforced Premium Defaulters (Sent out by IRAS)",
    "affectedCohortDescription": "Insureds who incurred premium debt and have not paid up.",
    "estimatedCohortSize": 400,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Chui Chein Sheun",
    "OICEmail": "Chui.Chein.Sheun@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW94_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Final Reminder Letter for Outstanding MSHL/CSHL Premiums",
    "scheme": "MSHL, CSHL",
    "description": "Insureds who incurred premiums debt for more than a year will be sent a final reminder letter to pay up before sending to IRAS for Enforcement.",
    "affectedCohortDescription": "Insureds who incurred premiums debt for more than a year",
    "estimatedCohortSize": 500,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Chui Chein Sheun",
    "OICEmail": "Chui.Chein.Sheun@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW95_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Outstanding MSHL Premium Payment Reminder Sent After Upgrade to IP",
    "scheme": "MSHL",
    "description": "Current payers of IP insured who incurred premium debt for the period they were covered under MSHL, prior to IP upgrade.",
    "affectedCohortDescription": "Current payers of IP insured who incurred premium debt for the period they were covered under MSHL, prior to IP upgrade.",
    "estimatedCohortSize": 150,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Chui Chein Sheun",
    "OICEmail": "Chui.Chein.Sheun@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW96_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Quarterly Recovery Letters to Insured/Parents",
    "scheme": "MSHL, CSHL",
    "description": "",
    "affectedCohortDescription": "Insured/parents who have outstanding MSHL/CSHL premiums.",
    "estimatedCohortSize": 13100,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW97_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-20T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Integrated Shield Plan Premium Notice Letter to Payer (Sent by Insurers)",
    "scheme": "IP",
    "description": "",
    "affectedCohortDescription": "New cover and existing insured with IP renewal in Jan 2025.",
    "estimatedCohortSize": 325000,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Jocelyn Low",
    "OICEmail": "Jocelyn.Low@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW98_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Additional Premium Support (APS) Invitation Packages",
    "scheme": "Additional Premium Support (APS)",
    "description": "",
    "affectedCohortDescription": "Insureds who incurred premiums debt and are eligible to apply for APS.",
    "estimatedCohortSize": 3272,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Grace Chua",
    "OICEmail": "Grace.Chua@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW99_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CSHL Welcome Letters",
    "scheme": "CSHL",
    "description": "",
    "affectedCohortDescription": `  i: All SCs and PRs turning 30
                                    ii: New SCs and PRs under Existing Cohort
                                    iii: Existing SCs and PRs under Existing Cohort`,
    "estimatedCohortSize": 7100,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Joycelyn Tan",
    "OICEmail": "Joycelyn.Tan@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW100_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-25T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CSHL Unsuccessful Premium Deduction Letters",
    "scheme": "CSHL",
    "description": "",
    "affectedCohortDescription": `All CareShield Life insureds with a change in their premium amount or insufficient MA will be notified via SMS (by default).`,
    "estimatedCohortSize": 2600,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW101_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-25T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CSHL Family Support Letters",
    "scheme": "CSHL",
    "description": "",
    "affectedCohortDescription": `Family members of CareSheld Life insureds who have an unsuccessful premium deduction twice will be identified as a payer to make premium payments for the insured. `,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW103_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CSHL Renewal Notification",
    "scheme": "CSHL",
    "description": "",
    "affectedCohortDescription": `CareShield Life insureds cover renewed in Jan '25, where the Renewal notification is sent 2 months prior (in Nov '24).`,
    "estimatedCohortSize": 50000,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Anita Hong",
    "OICEmail": "Anita.Hong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW104_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-25T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "ESH Renewal Notification",
    "scheme": "ESH",
    "description": "",
    "affectedCohortDescription": `ElderShield insureds with cover renewed in Jan '25 where the Renewal notification is sent 2 months prior (in Nov '24). `,
    "estimatedCohortSize": 16500,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Anita Hong",
    "OICEmail": "Anita.Hong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW105_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-12T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "ESH Unsuccessful Premium Deduction Notification",
    "scheme": "ESH",
    "description": "",
    "affectedCohortDescription": `All ElderShield payers with insufficient MA for ESH premium deduction will be notified via SMS (by default).`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HID) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW106_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-05T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "ESH Termination Notification",
    "scheme": "ESH",
    "description": "",
    "affectedCohortDescription": `Insureds who request to terminate ESH cover or non-payment of ESH premiums to renew/reinstate ESH cover.`,
    "estimatedCohortSize": 150,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Anita Hong",
    "OICEmail": "Anita.Hong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW107_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-05T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "ESH Paid Up Notification",
    "scheme": "ESH",
    "description": "",
    "affectedCohortDescription": `Insureds who request to terminate ESH cover or non-payment of ESH premiums to renew/reinstate ESH cover and policy has been converted to paid-up.`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Anita Hong",
    "OICEmail": "Anita.Hong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW108_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-21T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Health Insurance Planner - Soft Launch",
    "scheme": "Health Insurance Planner",
    "description": "",
    "affectedCohortDescription": `All SC/PRs with Singpass can access the planner`,
    "estimatedCohortSize": 7000,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Joycelyn Tan",
    "OICEmail": "Joycelyn.Tan@cpf.com.sg",
    // "reportStatus": "Completed"
}

// HED
const ROW111_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-07T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Inform Students of Repayment and Monthly Instalment Amounts",
    "scheme": "Repayment packages (R01)",
    "description": "Repayment packages (R01)  to students to inform them of commencement date of repayments and monthly instalment amounts",
    "affectedCohortDescription": `Students under EDN Scheme`,
    "estimatedCohortSize": 7000,
    "cluster": "SVC",
    "group": "HIG",
    "department": "HED",
    "OIC": "AD(HE) Yong Cai Xian",
    "OICEmail": "Yong.Cai.Xian@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW112_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-20T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Changes to the premium deduction process for Dependants’ Protection Scheme (DPS)",
    "scheme": "Dependants’ Protection Scheme (DPS)",
    "description": "",
    "affectedCohortDescription": `DPS policyholders who are funding their DPS premiums with their SA`,
    "estimatedCohortSize": 5500,
    "cluster": "SVC",
    "group": "HIG",
    "department": "HED",
    "OIC": "AD(HE) Tay Ming Ting",
    "OICEmail": "Tay.Ming.Ting@cpf.com.sg",
    // "reportStatus": "Completed"
}

// RSG
const ROW120_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-06T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Mobile push notification to members (age >= 55) who has met the CFRS",
    "scheme": "CPF OA, CPF SA",
    "description": "Mobile push notification to members (age >= 55) who has met the CFRS as of end Dec 2024. For members with no monies in their Ordinary Account (OA) and Special Account (SA), we will only reach out to members who have received top-ups before.",
    "affectedCohortDescription": ` Members (age >= 55) who has met the CFRS as of end Dec 2024. For members with no monies in their Ordinary Account (OA) and Special Account (SA), we will only reach out to members who have received top-ups before.`,
    "estimatedCohortSize": 200000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RSD",
    "OIC": "AD (RS) Joanne Ng Xin Yi",
    "OICEmail": "Joanne.Ng.Xin.Yi@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW120_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "Yes",
    "notificationTypes": ["Mobile Push Notification"],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": "Members are encouraged to make top-ups.",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `NA`
}

const ROW121_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-18T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Scheduled downtime for RSTU form",
    "scheme": "RSTU",
    "description": "",
    "affectedCohortDescription": `All cohort`,
    "estimatedCohortSize": 4000000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RSD",
    "OIC": "AD (RS) Joanne Ng Xin Yi",
    "OICEmail": "Joanne.Ng.Xin.Yi@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW121_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "Yes",
    "announcementTypes": ["Banner in SCD Appointment Page", "Banner in RSTU Form Page"],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "No",
    "actionRequiredDetails": "",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `Banner deployed in SCD appointment page and RSTU form page 2 January 2025 to inform member that RSTU form will be closed on 18 and 19 January 2025`
}

const ROW122_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Implementation of Enhancements to Matched Retirement Savings Scheme (MRSS)",
    "scheme": "MRSS",
    "description": "",
    "affectedCohortDescription": `MRSS-eligible members`,
    "estimatedCohortSize": 800000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RSD",
    "OIC": "SM(RS) Tan Shu Liang",
    "OICEmail": "Tan.Shu.Liang@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW122_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "Yes",
    "generateInterestDetails": "Increase in MRSS matching grant",
    "haveAnnouncement": "Yes",
    "announcementTypes": ["Press Release"],
    "haveNotification": "Yes",
    "notificationTypes": ["Push Notification"],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": "To carry out cash top-up(s) to enjoy MRSS matching grant",
    "dataInsightDetails": "NA",
    "initiativesDetails": "In tandem with Enhanced MRSS implementation, new FAQs, an MRSS explanatory video, and infographics will be uploaded to the MRSS web page on 1 Jan 2025 for members' information.",
    "eventWriteUp": `
                    To prioritise Special Account Closure (SAC) implementation, notifications are intentionally planned to be sent from early to mid-Feb 2025.
                    Enhanced MRSS implementation will be mentioned in the Press Release for SAC, which is tentatively scheduled for 19 Jan 2025.
                    The press release will also indicate that members will only receive MRSS notifications in Feb 2025 and that they can self-help to check their eligibility status via online tools (i.e. MRSS eligibility checker), which will be available to members from 13 Jan onwards.`
}

const ROW123_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Implementation of Raised Enhanced Retirement Sum (ERS)",
    "scheme": "ERS",
    "description": "",
    "affectedCohortDescription": `CPF members who are age 55 and above in 2025`,
    "estimatedCohortSize": 1000000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RSD",
    "OIC": "AD (RS) Joanne Ng Xin Yi ",
    "OICEmail": "Joanne.Ng.Xin.Yi@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW123_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "Yes",
    "announcementTypes": ["Banner on CPF Website"],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "No",
    "actionRequiredDetails": "",
    "dataInsightDetails": "NA",
    "initiativesDetails": "FAQ Update",
    "eventWriteUp": `FAQs will be revised on 1 Jan 2025 to reflect the new ERS value and the RSTU scheme page will also be updated to include a banner on the raising of ERS for member's information.
                    `
}

// RIU
const ROW124_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-20T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Closure and Transfer of Special Account (SA)",
    "scheme": "CPF SA",
    "description": "One-time notification via email and hardcopy letter in 4 languages to aged 55 and above members to inform them that their SA has been closed, and the SA savings transferred to RA/OA",
    "affectedCohortDescription": `CPF members who are age 55 and above in 2025`,
    "estimatedCohortSize": 1400000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RIU",
    "OIC": "DD(RIU) Xia Yin",
    "OICEmail": "Xia.Yin@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW124_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "Yes",
    "announcementTypes": ["Budget Speech", "Press Release"],
    "haveNotification": "Yes",
    "notificationTypes": ["Emails", "Letters"],
    "notificationDetails": "",
    "haveActionRequired": "No",
    "actionRequiredDetails": "",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": ``
}

const ROW125_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-19T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Launch of Transfer Retirement Account contributions to Ordinary Account",
    "scheme": "CPF SA, OA, RA",
    "description": "Launch of Transfer Retirement Account contributions to Ordinary Account for withdrawal form for Working Winnies (Members who have contributions credited to their RA after the implementation of SA Closure)",
    "affectedCohortDescription": `Age 55 and above members who have not met their FRS and were able to withdraw part of their SA contributions before the closure of their SA. `,
    "estimatedCohortSize": 98000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RIU",
    "OIC": "DD(RIU) Xia Yin",
    "OICEmail": "Xia.Yin@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW125_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": "Members need to fill in 55-withdrwal form in order to withdraw the RA contribution transferred to OA.",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": `While the form is for members to transfer a portion of the RA contribution to OA for withdrawal, members  will be reminded of the SA closure policy which generally have negative sentiments from the public.
                    With SA contributions credited to RA after SA closure, they will be allowed to withdraw a portion of their RA contributions as a concessionary measure.`
}

// RWD
const ROW126_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-01-28T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "RSS alive verification exercise",
    "scheme": "RSS",
    "description": "Members need to write in or go to the counter to confirmation their alive status to continue receiveing their payout to their bank account.",
    "affectedCohortDescription": `RSS members above 100yo receiving payouts to their bank account`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "M(RW) Xu Zhirong",
    "OICEmail": "Xu.Zhirong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW126_CIA = {
    "perceivedUnhappiness": "No",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "No",
    "generateInterestDetails": "",
    "haveAnnouncement": "No",
    "announcementTypes": [],
    "haveNotification": "No",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "Yes",
    "actionRequiredDetails": "Members need to write in or go to the counter to confirmation their alive status to continue receiveing their payout to their bank account.",
    "dataInsightDetails": "NA",
    "initiativesDetails": "NA",
    "eventWriteUp": ``
}

const ROW127_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-02T16:00:00.000Z"),
    "endDate": new Date("2026-01-31T16:00:00.000Z"),
    "frequency": "Yearly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "RSS/RLE Monthly Payment Run",
    "scheme": "RSS , RLE",
    "description": "",
    "affectedCohortDescription": `RSS members with OSRA balances of less than $350`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "AM(RW) Arina Lim",
    "OICEmail": "Arina.Lim@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW128_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-12T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Monthly notification on auto-starting payouts for pre-1948 members",
    "scheme": "RSS",
    "description": "",
    "affectedCohortDescription": `Pre-1948 RSS members who have not started their monthly payouts, and have monies in their OSRA to be streamed out as monthly payouts`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "AM(RW) Arina Lim",
    "OICEmail": "Arina.Lim@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW129_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification to members on monthly payouts prior to PEA",
    "scheme": "RSS",
    "description": "About three months before members’ payout eligibility age (PEA), a notification will be sent to them via a hardcopy letter + an additional digital mode of email if members have registered email address in Board’s records. Members will be informed of the options they have regarding their monthly payouts. ",
    "affectedCohortDescription": `Affects members reaching PEA in 3 months`,
    "estimatedCohortSize": 6000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "M(RW) Yongjun Cai",
    "OICEmail": "Yongjun.Cai@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW130_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-20T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF LIFE Acknowledgement Letters",
    "scheme": "CPF LIFE",
    "description": "CPF LIFE Acknowledgement Letters to members who sign up for CPF LIFE via hardcopy application forms",
    "affectedCohortDescription": `Members who sign up for CPF LIFE via hardcopy application forms`,
    "estimatedCohortSize": 100,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "DD(RW) Adeline Ho",
    "OICEmail": "Adeline.Ho@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW131_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-27T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF LIFE Policy Issuance Letters",
    "scheme": "CPF LIFE",
    "description": "CPF LIFE Policy Issuance Letters to be sent to members who join CPF LIFE",
    "affectedCohortDescription": `Members who join CPF LIFE`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "DD(RW) Adeline Ho",
    "OICEmail": "Adeline.Ho@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW132_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-27T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF LIFE Auto-split Policy Issuance Letters ",
    "scheme": "CPF LIFE",
    "description": "",
    "affectedCohortDescription": `Members who will be reaching payout eligibility age in 1 months`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "DD(RW) Adeline Ho",
    "OICEmail": "Adeline.Ho@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW133_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-14T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "55th Birthday Packages to Members",
    "scheme": "",
    "description": "Reaching 55 packages sent to members approximately three months before their 55th birthday",
    "affectedCohortDescription": `Affects members turning 55`,
    "estimatedCohortSize": 5500,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "M(RW) Vanessa Ong ",
    "OICEmail": "Vanessa.Ong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW134_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-02T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "LPSA-3 months for members reaching 70",
    "scheme": "LPSA",
    "description": "LPSA-3 months for members reaching 70",
    "affectedCohortDescription": `Members reaching age 70 in August 2022`,
    "estimatedCohortSize": 2000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "AM(RW) Arina Lim",
    "OICEmail": "Arina.Lim@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW135_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-27T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF LIFE Change of Policy Issuance Letters",
    "scheme": "CPF LIFE",
    "description": "CPF LIFE Policy Issuance Letters for members who went through a change of plan",
    "affectedCohortDescription": `Members who apply to change their plan`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "AD(RW) Sherlene Teh",
    "OICEmail": "Sherlene.Teh@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW136_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-27T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF LIFE Change of Policy Acknowledgement Letters",
    "scheme": "CPF LIFE",
    "description": "CPF LIFE Acknowledgement Letters to members who applied for a change of plan",
    "affectedCohortDescription": `Members who apply to change their plan`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "AD(RW) Sherlene Teh",
    "OICEmail": "Sherlene.Teh@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW137_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-16T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Reminder Notification to New CPF LIFE Members",
    "scheme": "CPF LIFE",
    "description": "A reminder notification will be sent to CPF LIFE members 2 months prior to their PEA, if they have not instructed us on their monthly payouts decisions after receiving the first notification sent to them at PEA-3months",
    "affectedCohortDescription": `Existing LIFE member who have not submitted their PMP form at PEA-2M`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "M(RW) Yongjun Cai",
    "OICEmail": "Yongjun.Cai@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW138_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-07T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Payout Revision for RSS members reaching 75 years old",
    "scheme": "RSS",
    "description": "",
    "affectedCohortDescription": `RSS members on reduced payouts who are reaching age 75 in February 2023`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "M(RW) Xu Zhirong",
    "OICEmail": "Xu.Zhirong@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW139_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-21T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF LIFE monthly payout review letters",
    "scheme": "CPF LIFE",
    "description": "",
    "affectedCohortDescription": `CPF LIFE members with inflows and outflows to their RA`,
    "estimatedCohortSize": 1000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RWD",
    "OIC": "M(RW) Dion Thong",
    "OICEmail": "Dion.Thong@cpf.com.sg",
    // "reportStatus": "Completed"
}

// NAC
const ROW144_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-21T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification Letter of Account Closure",
    "scheme": "",
    "description": "Daily Notification letters to inform newly renounced foreigners of account closure",
    "affectedCohortDescription": `Foreigners with CPF account`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "SM(NAC) Erika Tedja",
    "OICEmail": "Erika.Tedja@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW145_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Weekly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Request for Additional Documents/Information for Account Closure",
    "scheme": "",
    "description": "Emails/Letters to members to request for additional documents and/or information (pertaining to FormSG)",
    "affectedCohortDescription": `Members who apply for account closure for non-SC and non-SPR `,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "SM (NAC) Eric HL Lim",
    "OICEmail": "Eric.HL.Lim@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW146_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Invitation letter to Deceased Members' Nominees",
    "scheme": "",
    "description": "Invitation letter to nominees to invite them to claim deceased's CPF savings",
    "affectedCohortDescription": `Nominees of deceased members`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "AD(NAC) Sharlene Lee ",
    "OICEmail": "Sharlee.Lee@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW147_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF D1 Form Submission Reminder Letter",
    "scheme": "",
    "description": "Reminder letter to remind nominees to submit CPF D1 form if they have yet to do so",
    "affectedCohortDescription": `Nominees of deceased members`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "AD(NAC) Sharlene Lee ",
    "OICEmail": "Sharlee.Lee@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW148_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Letter to request for additional supporting documents ",
    "scheme": "",
    "description": "Letter to request for additional supporting documents",
    "affectedCohortDescription": `Nominees/ next of kin of deceased members`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "AD(NAC) Sharlene Lee ",
    "OICEmail": "Sharlee.Lee@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW149_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Inform Estate Admin To Submit Grant of Probate/ Letter of Administration",
    "scheme": "",
    "description": "Letter to inform Estate Admin to submit Grant of Probate/ Letter of Administration and estate securities account number for claim of deceased's discounted Singtel shares",
    "affectedCohortDescription": `Estate Administrator`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "AD(NAC) Sharlene Lee ",
    "OICEmail": "Sharlee.Lee@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW150_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Auto-Supplementary Letters for Claiming of Outstanding CPF Balances",
    "scheme": "",
    "description": "Auto-Supplementary letters to invite members/nominees to claim any outstanding CPF balance",
    "affectedCohortDescription": `Members/ nominees who have withdrawn under account closure for non-SC and non-SPR and Death`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "M(NAC) Rajendran Meena",
    "OICEmail": "Rajendran.Meena@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW153_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2025-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Letters to advise returning ex-SC/SPR on amount to refund",
    "scheme": "",
    "description": "",
    "affectedCohortDescription": `Members`,
    "estimatedCohortSize": 200,
    "cluster": "SVC",
    "group": "RIG",
    "department": "NAC",
    "OIC": "AM(NAC) Phoebe Lim",
    "OICEmail": "Phoebe.Lim@cpf.com.sg",
    // "reportStatus": "Completed"
}

// AIS
const ROW158_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-03T16:00:00.000Z"),
    "endDate": new Date("2026-12-31T16:00:00.000Z"),
    "frequency": "Yearly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Launch of YSOA",
    "scheme": "",
    "description": "Launch of YSOA - Members will be able to view their YSOA online on 1 Jan of the new year. Hardcopy YSOA will be mailed out in batches from end January.",
    "affectedCohortDescription": `Full cohort`,
    "estimatedCohortSize": 4000000,
    "cluster": "PCD",
    "group": "PSR",
    "department": "AIS",
    "OIC": "DD(AIS) Justin Chang",
    "OICEmail": "Justin.Chang@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW159_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-06T16:00:00.000Z"),
    "endDate": new Date("2026-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Email Notification of MSOA",
    "scheme": "",
    "description": "CPF Monthly Transaction Statement (MSOA) will be sent via email notification to all SCPRs who have transactions in the previous month and have a valid email address. ",
    "affectedCohortDescription": `SCPRs with transactions in the previous month and with valid email address`,
    "estimatedCohortSize": 2000000,
    "cluster": "PCD",
    "group": "PSR",
    "department": "AIS",
    "OIC": "AD(AIS) Adele HO ",
    "OICEmail": "Adele.Ho@cpf.com.sg",
    // "reportStatus": "Completed"
}

const ROW160_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-06T16:00:00.000Z"),
    "endDate": new Date("2026-12-31T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Synchronisation Exercise of Member's Singpass and CPF Contact Details",
    "scheme": "",
    "description": "Singpass Ingestion and notifications to CPF members who have different Singpass contact details from their CPF contact details",
    "affectedCohortDescription": `i. SC/PR who are found to have Singpass contact details but not CPF contact details
                                    ii. SC/PR who are found to have different Singpass and CPF contact details `,
    "estimatedCohortSize": 470000,
    "cluster": "PCD",
    "group": "PSR",
    "department": "AIS",
    "OIC": "AD(AIS) Pamela Tan",
    "OICEmail": "Pamela.Tan@cpf.com.sg",
    // "reportStatus": "Completed"
}

// RHS
const ROW165_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-01-17T16:00:00.000Z"),
    "endDate": new Date("2026-11-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Acknowledgement of RHS Participants' Efforts",
    "scheme": "",
    "description": `1. Send notification letters and email/SMS/push via ACS to RHS participants to inform them on to take part in Wave 6
                    2. Thank you email/SMS/push via ACS to selected members to thank them for participation in the RHS
                    3. Reminder email/SMS/push via ACS to selected members to remind them to participate in the RHS
                    4. Survey Vendor will be calling respondents for Quality control purposes`,
    "affectedCohortDescription": `RHS Participants (i.e. selected group of members)`,
    "estimatedCohortSize": 2000,
    "cluster": "PCD",
    "group": "SRG",
    "department": "RHS",
    "OIC": "Neo Ming Yuan",
    "OICEmail": "Neo.Ming.Yuan@cpf.com.sg",
    // "reportStatus": "Completed"
}

const JAN_EVENTS = [
    { "Event Details": ROW4_DETAILS, "Impact Assessment": ROW4_CIA },
    { "Event Details": ROW5_DETAILS_W1, "Impact Assessment": template_CIA },
    { "Event Details": ROW5_DETAILS_W2, "Impact Assessment": template_CIA },
    { "Event Details": ROW5_DETAILS_W3, "Impact Assessment": template_CIA },
    { "Event Details": ROW6_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW7_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW8_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW9_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW10_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW11_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW12_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW13_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW14_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW15_DETAILS_1, "Impact Assessment": ROW15_CIA },
    { "Event Details": ROW15_DETAILS_2, "Impact Assessment": ROW15_CIA },
    { "Event Details": ROW16_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW24_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW25_DETAILS, "Impact Assessment": ROW25_CIA },
    { "Event Details": ROW26_DETAILS, "Impact Assessment": ROW26_CIA },
    { "Event Details": ROW45_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW46_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW47_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW48_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW49_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW50_DETAILS, "Impact Assessment": ROW50_CIA },
    { "Event Details": ROW53_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW54_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW55_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW56_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW57_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW60_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW61_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW62_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW67_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW68_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW69_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW70_DETAILS, "Impact Assessment": ROW70_CIA },
    { "Event Details": ROW76_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW77_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW78_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW79_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW80_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW84_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW85_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW86_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW87_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW88_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW89_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW90_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW91_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW92_93_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW94_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW95_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW96_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW97_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW98_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW99_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW100_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW101_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW103_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW104_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW105_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW106_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW107_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW108_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW111_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW112_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW120_DETAILS, "Impact Assessment": ROW120_CIA },
    { "Event Details": ROW121_DETAILS, "Impact Assessment": ROW121_CIA },
    { "Event Details": ROW122_DETAILS, "Impact Assessment": ROW122_CIA },
    { "Event Details": ROW123_DETAILS, "Impact Assessment": ROW123_CIA },
    { "Event Details": ROW124_DETAILS, "Impact Assessment": ROW124_CIA },
    { "Event Details": ROW125_DETAILS, "Impact Assessment": ROW125_CIA },
    { "Event Details": ROW126_DETAILS, "Impact Assessment": ROW126_CIA },
    { "Event Details": ROW127_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW128_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW129_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW130_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW131_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW132_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW133_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW134_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW135_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW136_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW137_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW138_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW139_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW144_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW145_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW146_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW147_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW148_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW149_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW150_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW153_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW158_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW159_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW160_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW165_DETAILS, "Impact Assessment": template_CIA }
]

export default JAN_EVENTS