const template_CIA = {
    "perceivedUnhappiness": "",
    "perceivedUnhappinessDetails": "",
    "generateInterest": "",
    "generateInterestDetails": "",
    "haveAnnouncement": "",
    "announcementTypes": [],
    "haveNotification": "",
    "notificationTypes": [],
    "notificationDetails": "",
    "haveActionRequired": "",
    "actionRequiredDetails": "",
    "dataInsightDetails": "",
    "initiativesDetails": "",
    "eventWriteUp": ``
}

// AMD
const ROW11_DETAILS = {
    "id": "",
    "type": "Existing with Changes",
    "embargoed": "No",
    "startDate": new Date("2025-03-20T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Press Release by  MOM on Earn and Save Bonus (ESB)",
    "scheme": "Majulah Package (MP), Earn and Save Bonus (ESB)",
    "description": "",
    "affectedCohortDescription": "Eligible Singaporeans born in 1973 or ealier",
    "estimatedCohortSize": 600000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW12_DETAILS = {
    "id": "",
    "type": "Existing with Changes",
    "embargoed": "No",
    "startDate": new Date("2025-03-20T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Bulk payment of Earn and Save Bonus (ESB)",
    "scheme": "Majulah Package (MP), Earn and Save Bonus (ESB)",
    "description": "",
    "affectedCohortDescription": "Eligible Singaporeans aged 50 & above in 2023",
    "estimatedCohortSize": 600000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW13_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-10T16:00:00.000Z"),
    "endDate": new Date("2025-09-30T16:00:00.000Z"),
    "frequency": "Custom",
    "frequencyInterval": 3,
    "customFrequency": "Monthly",
    "selectedDay": "Third Monday of the Month",
    "title": "Notify members of SSS payment",
    "scheme": "Silver Support Scheme (SSS)",
    "description": "Send SMS and letter to eligible citizens to notify SSS payment",
    "affectedCohortDescription": "Eligible Singaporeans aged 65 and above",
    "estimatedCohortSize": 250000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "AD(AMD) Lim Lan Si",
    "OICEmail": "Lim.Lan.Si@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW14_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-10T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 3,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Quarterly SSS payment",
    "scheme": "Silver Support Scheme (SSS)",
    "description": "",
    "affectedCohortDescription": "Eligible Singaporeans aged 65 and above",
    "estimatedCohortSize": 250000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Yvonne Chong",
    "OICEmail": "Yvonne.Chong@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW16_DETAILS = {
    "id": "",
    "type": "Existing with Changes",
    "embargoed": "No",
    "startDate": new Date("2025-03-01T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Allot EEs / PWs WIS",
    "scheme": "Workfare Income Supplement (WIS)",
    "description": "Monthly run to allot EEs / PWs WIS after capturing late CPF contributions/ adjustments",
    "affectedCohortDescription": "Low-wage workers",
    "estimatedCohortSize": 10000,
    "cluster": "SVC",
    "group": "ASG",
    "department": "AMD",
    "OIC": "SDD(AMD) Chua Mei Ling",
    "OICEmail": "Chua.Mei.Ling@cpf.com.sg",
    "reportStatus": "Completed"
}

// COM
const ROW28_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 3,
    "customFrequency": null,
    "selectedDay": null,
    "title": "What's Next with CPF eDM",
    "scheme": "",
    "description": "",
    "affectedCohortDescription": "Subscribers",
    "estimatedCohortSize": 1700000,
    "cluster": "PCD",
    "group": "COM",
    "department": "MPD",
    "OIC": "DD(MP) Joanne Lim",
    "OICEmail": "Joanne.Lim@cpf.com.sg",
    "reportStatus": "Completed"
}

// CSD
const ROW65_DETAILS_M = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Refund of excess Volwuntary Contributions (VCs)",
    "scheme": "VC",
    "description": `Bulk refund of excess Voluntary Contributions to members whose total contributions have exceeded the Annual Limit for 2024`,
    "affectedCohortDescription": "Members",
    "estimatedCohortSize": 4000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CSD",
    "OIC": "Ernest Ng",
    "OICEmail": "Ernest.Ng@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW65_DETAILS_E = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Refund of excess Volwuntary Contributions (VCs)",
    "scheme": "VC",
    "description": `Reminder letters to employers whose employees have exceeded the Additional Wage Ceiling and Annual Limit (2018-2022)`,
    "affectedCohortDescription": "Employers",
    "estimatedCohortSize": 5000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CSD",
    "OIC": "Nadeera Shahrafay",
    "OICEmail": "Nadeera.Shahrafay@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW66_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CPF EZPay Optimal Submission Checker ",
    "scheme": "EZPay",
    "description": "",
    "affectedCohortDescription": "Employers",
    "estimatedCohortSize": 2000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "CSD",
    "OIC": "SDD(CS) Erica Aw",
    "OICEmail": "Erica.Aw@cpf.com.sg",
    "reportStatus": "Completed"
}

// SED
const ROW70_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Disbursement of Platform Workers CPF Transition Support",
    "scheme": "CPF Transition Support",
    "description": "",
    "affectedCohortDescription": "Platform Workers",
    "estimatedCohortSize": 88000,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "AD(SED) Yang Yiming",
    "OICEmail": "Yang.Yiming@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW71_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Weekly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "CAYE Welcome letter",
    "scheme": "CAYE",
    "description": "",
    "affectedCohortDescription": "CAYE SEPs",
    "estimatedCohortSize": 170,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "DD(SED) Jasimah Majid",
    "OICEmail": "Jasimah.Majid@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW72_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-15T16:00:00.000Z"),
    "endDate": new Date("2025-12-30T16:00:00.000Z"),
    "frequency": "Weekly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Refund of excess Contribute As You Earn(CAYE) contributions",
    "scheme": "CAYE",
    "description": "",
    "affectedCohortDescription": "CAYE SEPs",
    "estimatedCohortSize": 40,
    "cluster": "SVC",
    "group": "ECE",
    "department": "SED",
    "OIC": "DD(SED) Jasimah Majid",
    "OICEmail": "Jasimah.Majid@cpf.com.sg",
    "reportStatus": "Completed"
}

// HID
const ROW112_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-26T16:00:00.000Z"),
    "endDate": new Date("2025-12-26T16:00:00.000Z"),
    "frequency": "Monthly",
    "frequencyInterval": 1,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Notification to Minor Overseas Singaporeans (OS) with Active Premium Suspension",
    "scheme": "",
    "description": "Notification to Minor Overseas Singaporeans (OS) with Active Premium Suspension after they turn 21",
    "affectedCohortDescription": "Minor OS aged 21 and above, with active premium suspension",
    "estimatedCohortSize": 100,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "DD(HI) Lu Zhijia",
    "OICEmail": "Lu.Zhijia@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW113_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-26T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Health Insurance Planner - Official Launch",
    "scheme": "Health Insurance Planner",
    "description": "",
    "affectedCohortDescription": `All SC/PRs with Singpass can access the planner`,
    "estimatedCohortSize": 100001,
    "cluster": "SVC",
    "group": "HFG",
    "department": "HID",
    "OIC": "SDD(HID) Joycelyn Tan",
    "OICEmail": "Joycelyn.Tan@cpf.com.sg",
    "reportStatus": "Completed"
}

// RSG
const ROW126_DETAILS = {
    "id": "",
    "type": "New",
    "embargoed": "No",
    "startDate": new Date("2025-03-26T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "New eService for recurring CPF transfers from OA to SA",
    "scheme": "CPF OA, RA",
    "description": "New eService for recurring CPF transfers from Ordinary Account to Retirement Account for members aged 55 and above",
    "affectedCohortDescription": "Members above 55 and above",
    "estimatedCohortSize": 85000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RSG",
    "OIC": "SM(Ng Suqi)",
    "OICEmail": "Ng.Suqi@cpf.com.sg",
    "reportStatus": "Completed"
}

const ROW127_DETAILS = {
    "id": "",
    "type": "Existing",
    "embargoed": "No",
    "startDate": new Date("2025-03-21T16:00:00.000Z"),
    "endDate": null,
    "frequency": "One-off",
    "frequencyInterval": null,
    "customFrequency": null,
    "selectedDay": null,
    "title": "Eligibility run for MRSS",
    "scheme": "MRSS",
    "description": "Second eligibility run for Matched Retirement Savings Scheme",
    "affectedCohortDescription": "Members above 55 and above",
    "estimatedCohortSize": 10000,
    "cluster": "SVC",
    "group": "RIG",
    "department": "RSG",
    "OIC": "SM(Tan Shu Liang)",
    "OICEmail": "Tan.Shu.Liang@cpf.com.sg",
    "reportStatus": "Completed"
}

const EVENTS = [
    { "Event Details": ROW11_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW12_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW13_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW14_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW16_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW28_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW65_DETAILS_M, "Impact Assessment": template_CIA },
    { "Event Details": ROW65_DETAILS_E, "Impact Assessment": template_CIA },
    { "Event Details": ROW66_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW70_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW71_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW72_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW112_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW16_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW113_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW126_DETAILS, "Impact Assessment": template_CIA },
    { "Event Details": ROW127_DETAILS, "Impact Assessment": template_CIA }
]

export default EVENTS